import { StyleSheet } from "react-native";

export const Styles = StyleSheet.create({

    pageTitle: {   
        fontFamily: 'Archivo',
        fontSize: 18,
        color: '#734D8C',
        fontWeight: '400',
        textAlign: 'center',
    },
    Card: {
        width: "100%",
        height: 214,
        backgroundColor: '#734D8C',
        borderRadius: 30,
        marginTop: 14,
        padding: 10,
    },
    simpleForm:{
        width: "100%",
        height: 61,
        backgroundColor: '#ffffff',
        borderRadius: 30,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 7,
        padding:18,
        marginTop: 15
    },
    input: {
        flexDirection: 'row',
        alignItems: 'center',
        width: "100%",
        height: 58,
        backgroundColor: '#ffffff',
        borderRadius: 30,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 7,
        marginTop: 10,
        justifyContent:'center',
        padding: 10 
    },
    inputSearch: {
        flexDirection: 'row',
        alignItems: 'center',
        width: "100%",
        height: 58,
        backgroundColor: '#ffffff',
        borderRadius: 30,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 7,
        marginTop: 10,
        padding: 15
    },
    socialLogin: {
        flexDirection:'row',
        justifyContent: 'center',
        alignItems:'center',
        width: 115,
        height: 58,
        borderRadius: 30,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 7,
        marginTop: 25, 
    },
    button: {
        justifyContent: 'center',
        backgroundColor: '#6D3F8C',
        borderRadius: 30,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 7,
        height: 58,
        width: 155,
        marginTop:20
    },
    textButton: {
        fontSize: 16,
        fontFamily: 'Archivo',
        color: '#FFFFFF',
        fontWeight: '400',
        textAlign: 'center',
    },
    textSocial: {
        fontSize: 16,
        fontFamily: 'Archivo',
        color: '#734D8C',
        fontWeight: '400',
        textAlign: 'center',
        marginVertical: 16,     
    },
    textInput: {
        fontFamily: 'Archivo',
        fontSize: 16,
        color: '#734D8C',
        fontWeight: '400',
        left:10,
        width:'90%'
    },
    textEsc: {
        fontFamily:'Archivo',
        fontSize: 10,
        color: '#734D8C',
        textAlign:'center'
    },
    text2: {
        fontFamily:'Archivo',
        fontSize: 16,
        color: '#000000',
        fontWeight: '700',
    },
    text3: {
        fontFamily: 'Archivo',
        fontSize: 20,
        color: '#000000',
        fontWeight: '700',
    },
    text4: {
        fontFamily: 'Archivo',
        fontSize: 20,
        color: '#000000',
        fontWeight: '400',
    },
    text5: {
        fontFamily:'Archivo',
        fontSize: 16,
        color: '#000000',
        fontWeight: '400',
    },
    text6: {
        fontFamily:'Archivo',
        fontSize: 12,
        color: 'white',
        fontWeight:'400'
    },
    text7: {
        fontSize: 16,
        fontFamily: 'Archivo',
        color: '#734D8C',
        fontWeight: '400',
        textAlign: 'center',   
    },
    form: {
        height: 100,
        backgroundColor: '#6D3F8C',
        borderRadius: 30,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 7,
        marginTop: 50,
        padding: 20,
        alignItems: 'center',
        justifyContent:'space-between',
        flexDirection: 'row',
    },
    textDisplay: {
        fontSize: 16,
        color: '#E7DCF2',
        fontWeight: '400',
        fontFamily: 'Archivo',
    },
    textDisplay2: {
        fontSize: 20,
        color: '#E7DCF2',
        fontWeight: '400',
        fontFamily: 'Archivo',
    },
    textVendas: {
        flexDirection: 'row', 
        marginVertical: 10, 
        justifyContent: 'space-between', 
        alignItems: 'center',
        fontFamily: 'Archivo',
    },

    formEnd: {
        backgroundColor: '#6D3F8C', 
        borderRadius: 30, 
        height: 70, 
        padding: 17, 
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 3,
        },
        shadowOpacity: 0.29,
        shadowRadius: 4.65,
        elevation: 7,
        flexDirection: 'row', 
        justifyContent: 'space-between', 
        alignItems: 'center',
    }
});